# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Financial Independence
#brief-intro: Save and Make Money
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://garyteck.github.io" # the base hostname & protocol for your site
favicon: favicon-32x32.png
permalink: /:year/:month/:day/:title/

# other links
#twitter_username: gaohaoyang126
#facebook_username: gaohaoyang.water
#github_username:  Gaohaoyang
email: test@financialindependence.com
#weibo_username: 3115521wh
#zhihu_username: gaohaoyang
#linkedIn_username: gaohaoyang
#dribbble_username:

description_footer: blogging my road to financial independence

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
#duoshuo_shortname: #hygblog
disqus_shortname: garyteck

# statistic analysis 统计代码
google_analytics_id: UA-78768145-1


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6

#facebook like box
fb-like-box: yes
fb-page-url: https://www.facebook.com/Financial-Independence-Online-1173489342814210
